cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url ,include
from django.contrib.auth import views
from django.urls import path, re_path






urlpatterns = [
   

      # Django JET dashboard URLS
    re_path('admin/', admin.site.urls),
    re_path(r'', include('registration.urls')),
    re_path(r'', include('login.urls')),
    re_path(r'', include('account.urls')),
    re_path(r'cart', include('cart.urls')),
    re_path(r'orders/', include('orders.urls')),
    re_path(r'', include('shop.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from . import views

app_name = 'shop'


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^vendorrequest/', views.vendorrequest, name='vendorrequest'),
    url(r'^Vendorfaqs/', views.Vendorfaqs, name='Vendorfaqs'),
    url(r'^log/', views.log, name='log'),
    url(r'^about/', views.about, name='about'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^mens/', views.mens, name='mens'),
    url(r'^womens/', views.womens, name='womens'),
    url(r'^decorbeauty/', views.decorbeauty, name='decorbeauty'),
    url(r'^homeaccesories/', views.homeaccesories, name='homeaccesories'),
    url(r'^shop/', views.product_list, name='product_list'),
    url(r'^negotiate/price', views.client_price, name='client_price'),
    url(r'^negotiate/', views.negotiate, name='negotiate'),
    

   
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail, name='product_detail'),

    url(r'^(?P<subcategory_slug>[-\w]+)/$',
        views.subcategory_list, name='product_list_by_subcategory'),
    url(r'^(?P<minicategory_slug>[-\w]+)/$',
        views.minicategory_list, name='product_list_by_minicategory')




]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/forms.py
from django import forms

class NegotiateForm(forms.Form):
    client_price = forms.CharField(label='Your price', max_length=100)

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, SubCategory, MiniCategory
from .forms import NegotiateForm
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from account.models import Client
from django.shortcuts import redirect


# @login_required(login_url='/accounts/login/')
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    return render(request, 'shop/product/list.html',   context={
        'category': category,
        'categories': categories,
        'products': products,
        'tab': 'shop',
        'local_css_urls': ["css3/easy-responsive-tabs.css",
                           "css3/material-kit.min1036.css",
                           "css3/demo.css",
                           "css3/vertical-nav.css"],
        'local_js_urls': ["core/jquery.min.js",
                          "core/popper.min.js",
                          "core/bootstrap-material-design.min.js",
                          "js3/vertical-nav.js",
                          "js3/material-kit.min1036.js",
                          "js3/demo.js",
                          "js3/buttons.js",
                          "js3/modernizr.js",
                          "js3/bootstrap.min.js",
                          "js3/plugins/moment.min.js ",
                          "js3/plugins/bootstrap-datetimepicker.js",
                          "js3/plugins/jquery.flexisel.js",
                          "js3/plugins/jquery.sharrre.js",
                          "js3/plugins/nouislider.min.js",
                          "js3/plugins/bootstrap-selectpicker.js",
                          "js3/plugins/bootstrap-tagsinput.js",
                          "js3/plugins/jasny-bootstrap.min.js"],
    })


def subcategory_list(request, subcategory_slug=None):
    subcategory = None
    subcategories = Category.SubCategory.objects.all()
    products = Product.subcategory.objects.filter(available=True)
    if category_slug:
        subcategory = get_object_or_404(SubCategory, slug=SubCategory_slug)
        products = Product.objects.filter(subcategory=subcategory)

    context = {

        'subcategory': subcategory,
        'subcategories': subcategories,
        'products': products,

    }
    return render(request, 'shop/product/sublist.html', context)


def minicategory_list(request, minicategory_slug=None):
    minicategory = None
    minicategories = Category.SubCategory.MiniCategory.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        minicategory = get_object_or_404(MiniCategory, slug=MiniCategory_slug)
        products = Product.objects.filter(minicategory=minicategory)

    context = {

        'minicategory': minicategory,
        'minicategories': minicategories,
        'products': products,

    }

    return render(request, 'shop/product/minilist.html', context)

# @login_required(login_url='/accounts/login/')
# def product_detail(request, id, slug):
#     product = get_object_or_404(Product, id=id, slug=slug, available=True)
#     cart_product_form = CartAddProductForm()
#     context = {
#         'product': product,
#         'cart_product_form': cart_product_form
#     }
#     return render(request, 'shop/product/detail.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html',
                  context={
                      'product': product,
                      'cart_product_form': cart_product_form,
                      'local_css_urls': ["css3/easy-responsive-tabs.css",
                                         "css3/material-kit.min1036.css",
                                         "css3/demo.css",
                                         "css3/vertical-nav.css"],
                      'local_js_urls': ["core/jquery.min.js",
                                        "core/popper.min.js",
                                        "core/bootstrap-material-design.min.js",
                                        "js3/vertical-nav.js",
                                        "js3/material-kit.min1036.js",
                                        "js3/demo.js",
                                        "js3/buttons.js",
                                        "js3/modernizr.js",
                                        "js3/bootstrap.min.js",
                                        "js3/plugins/moment.min.js ",
                                        "js3/plugins/bootstrap-datetimepicker.js",
                                        "js3/plugins/jquery.flexisel.js",
                                        "js3/plugins/jquery.sharrre.js",
                                        "js3/plugins/nouislider.min.js",
                                        "js3/plugins/bootstrap-selectpicker.js",
                                        "js3/plugins/bootstrap-tagsinput.js",
                                        "js3/plugins/jasny-bootstrap.min.js"],
                  })


# homepage view

def home(request, category_slug=None, subcategory_slug=None, minicategory_slug=None):
    category = None
    subcategory = None
    minicategory = None
    categories = Category.objects.all()
    subcategories = SubCategory.objects.all()
    minicategories = MiniCategory.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        subcategories = SubCategory.objects.filter(category=category)

    # if subcategory_slug:
    #     subcategory = get_object_or_404(SubCategory, slug=subcategory_slug)
    #     minicategories = MiniCategory.objects.filter(available=True)

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'subcategories': subcategories,
        'minicategories ': minicategories,
        'subcategory': subcategory,
        'minicategory': minicategory,
    }

    return render(request, 'shop/homepage/page/home.html',   context={
        'category': category,
        'categories': categories,
        'products': products,
        'subcategories': subcategories,
        'minicategories': minicategories,
        'subcategory': subcategory,
        'minicategory': minicategory,

        'tab': 'shop',
        'local_css_urls': ["css3/easy-responsive-tabs.css",
                           "css3/material-kit.min1036.css",
                           "css3/demo.css",
                           "css3/vertical-nav.css"],
        'local_js_urls': ["core/jquery.min.js",
                          "core/popper.min.js",
                          "core/bootstrap-material-design.min.js",
                          "js3/vertical-nav.js",
                          "js3/material-kit.min1036.js",
                          "js3/demo.js",
                          "js3/buttons.js",
                          "js3/modernizr.js",
                          "js3/bootstrap.min.js",
                          "js3/plugins/moment.min.js ",
                          "js3/plugins/bootstrap-datetimepicker.js",
                          "js3/plugins/jquery.flexisel.js",
                          "js3/plugins/jquery.sharrre.js",
                          "js3/plugins/nouislider.min.js",
                          "js3/plugins/bootstrap-selectpicker.js",
                          "js3/plugins/bootstrap-tagsinput.js",
                          "js3/plugins/jasny-bootstrap.min.js"],
    })


def log(request):
    return render(request, 'shop/product/login2.html', {
        'tab': 'registration',
        'local_css_urls': ["css3/easy-responsive-tabs.css",
                           "css3/material-kit.min1036.css",
                           "css3/demo.css",
                           "css3/vertical-nav.css"],
        'local_js_urls': ["core/jquery.min.js",
                          "core/popper.min.js",
                          "core/bootstrap-material-design.min.js",
                          "js3/vertical-nav.js",
                          "js3/material-kit.min1036.js",
                          "js3/demo.js",
                          "js3/buttons.js",
                          "js3/modernizr.js",
                          "js3/bootstrap.min.js",
                          "js3/plugins/moment.min.js ",
                          "js3/plugins/bootstrap-datetimepicker.js",
                          "js3/plugins/jquery.flexisel.js",
                          "js3/plugins/jquery.sharrre.js",
                          "js3/plugins/nouislider.min.js",
                          "js3/plugins/bootstrap-selectpicker.js",
                          "js3/plugins/bootstrap-tagsinput.js",
                          "js3/plugins/jasny-bootstrap.min.js"],
    })


def vendorrequest(request):
    return render(request, 'shop/homepage/page/vendorrequest.html', {
        'tab': 'vendor',
        'local_css_urls': ["css3/easy-responsive-tabs.css",
                           "css3/material-kit.min1036.css",
                           "css3/demo.css",
                           "css3/vertical-nav.css"],
        'local_js_urls': ["js3/vertical-nav.js",
                          "js3/material-kit.min1036.js",
                          "js3/demo.js",
                          "js3/buttons.js",
                          "js3/modernizr.js",

                          "js3/jquery.min.js",
                          "js3/bootstrap.min.js",

shop/views/forgot_password.py
import json
import random, string
from django.shortcuts import render
from django.core import serializers
from landpage.form import ForgotPasswordForm
from django.http import HttpResponse
from django.conf import settings
from django.contrib.auth.models import User
from django.conf import settings
from django.core.mail import send_mail

def forgot_password_page(request):
    form = ForgotPasswordForm()
    return render(request, 'offlandpage/page/forgot_password.html',{
        'form': form,
        'tab': 'forget_password',
        'local_css_urls': ["css/offlandpage.css",
                            "bower_components/bootstrap/dist/css/bootstrap.min.css"],
        'local_js_urls': ["bower_components/jquery/dist/jquery.min.js",
                           "bower_components/bootstrap/dist/js/bootstrap.min.js",],
    })


def reset_password(request):
    response_data = {'status' : 'failure', 'message' : 'unknown error occured' }
    if request.is_ajax():
        if request.method == 'POST':
            form = ForgotPasswordForm(request.POST)
            # Validate the form: the captcha field will automatically
            # check the input
            if form.is_valid():
                # Get the email and then create a random password for the client
                # and send the client the new password to their email address.
                email = request.POST['email']
                new_password = create_random_password(email)
                response_data = send_email(email, new_password)
            else:
                response_data = {'status' : 'failed', 'message' : json.dumps(form.errors)}
    return HttpResponse(json.dumps(response_data), content_type="application/json")


def random_word(length):
    return ''.join(random.choice("abcdefghijklmnopqrstuvwxyz123467890") for i in range(length))


def create_random_password(email):
    # Create new password
    new_password = random_word(8)
    
    # Update the user account
    user = User.objects.get(email=email)
    user.set_password(new_password)
    user.save()
    
    # Return the new password
    return new_password


def send_email(email, new_password):
    if settings.EMAIL_HOST_USER is '' or settings.EMAIL_HOST_PASSWORD is '':
        return {'status' : 'failed', 'message' : 'cannot change password, emailer is offline, please check back later' }
    
    text = "Your new password is: " + new_password
            
    send_mail(
        "New Password",
        text,
        settings.EMAIL_HOST_USER,
        [email],
        fail_silently=False
    )
    return {'status' : 'success', 'message' : 'successfully registered' }

shop/views/google.py
from django.shortcuts import render
from django.core import serializers
import json
from django.http import HttpResponse
from django.conf import settings


def google_verify_page(request):
    return render(request, 'misc/google.html',{})

shop/views/landpageprod.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings

shop/views/privacy.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings


def privacy_page(request):
    return render(request, 'offlandpage/page/privacy.html',{
        'tab': 'privacy',
        'local_css_urls': ["css/offlandpage.css",
                            "bower_components/bootstrap/dist/css/bootstrap.min.css"],
        'local_js_urls': ["bower_components/jquery/dist/jquery.min.js",
                           "bower_components/bootstrap/dist/js/bootstrap.min.js",],
    })

shop/views/terms.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings


def terms_page(request):
    return render(request, 'offlandpage/page/terms.html',{
        'tab': 'terms',
        'local_css_urls': ["css/offlandpage.css",
                            "bower_components/bootstrap/dist/css/bootstrap.min.css"],
        'local_js_urls': ["bower_components/jquery/dist/jquery.min.js",
                           "bower_components/bootstrap/dist/js/bootstrap.min.js",],
    })

shop/views/txt.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings


def robots_txt_page(request):
    return render(request, 'misc/robots.txt', {}, content_type="text/plain")


def humans_txt_page(request):
    return render(request, 'misc/humans.txt', {}, content_type="text/plain")


def terms_txt_page(request):
    return render(request, 'misc/terms.txt', {}, content_type="text/plain")


def privacy_txt_page(request):
    return render(request, 'misc/privacy.txt', {}, content_type="text/plain")

shop/templates/shop/homepage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="description" content="jadili mall ">
    <meta name="keywords" content="">
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <title>{% block title %}jadili mall {% endblock %}</title>  <!--Curio On-line -->
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

    <link rel="shortcut icon" type="image/png" href="{% static 'images/u.png' %}"/>
 
 

    {% for local_css_url in local_css_urls %}
    <link rel="stylesheet" href="{% static local_css_url %}">
{% endfor %}


<!-- {% for local_js_url in local_js_urls %}
<script src="{% static local_js_url %}"></script>
{% endfor %} -->
 <!-- sumo ------------------------->
 <script async>(function(s,u,m,o,j,v){j=u.createElement(m);v=u.getElementsByTagName(m)[0];j.async=1;j.src=o;j.dataset.sumoSiteId='148c6592f79b637bc1532c3bb15a112e009b0322f6b974ba993d38c00952da3b';v.parentNode.insertBefore(j,v)})(window,document,'script','//load.sumo.com/');</script>
 <!-- end sumo ------------------------->
 <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
   <!-- //for bootstrap working -->
   <link href="https://fonts.googleapis.com/css?family=Caveat|Gloria+Hallelujah|Handlee|Modak|Nanum+Pen+Script|Roboto|Source+Sans+Pro&display=swap" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>
    <script>
        UPLOADCARE_PUBLIC_KEY = "4b92b91744f8fad64594";
      </script>
 <script charset="utf-8" src="https://ucarecdn.com/libs/widget/3.6.0/uploadcare.full.min.js"></script>

</head>
<body class="index-page sidebar-collapse">
{% include 'shop/homepage/navbar.html' %}
{% block content %}


{% endblock %}
<!--   Core JS Files   -->


{% include 'shop/homepage/page/js.html' %}

{% for local_js_url in local_js_urls %}
<script src="{% static local_js_url %}"></script>
{% endfor %}
<script language="JavaScript" type="text/javascript">
    $(document).ready(function(){
      $('.carousel').carousel({
        interval: 3000
      })
    });    
  </script>
 

</body>
</html>

shop/templates/shop/homepage/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="jadili mall ">
    <meta name="keywords" content="">
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <title>{% block title %}jadili mall {% endblock %}</title>  <!--Curio On-line -->
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

    <link rel="shortcut icon" type="image/png" href="{% static 'images/u.png' %}"/>
    <!-- <link type="text/css" rel="stylesheet" href="https://bbbootstrap.com/assets/css/reset.css">
    <link type="text/css" rel="stylesheet" href="https://bbbootstrap.com/assets/css/plugins.css">
    <link type="text/css" rel="stylesheet" href="https://bbbootstrap.com/assets/css/style.css?version=10.3">
    <link type="text/css" rel="stylesheet" href="https://bbbootstrap.com/assets/css/color.css">
  
    <link rel="shortcut icon" href="https://i.imgur.com/msO7f5I.png">
    <link rel="stylesheet" href="https://res.cloudinary.com/dxfq3iotg/raw/upload/v1568904751/balloon.min.css">
 -->

  
    <script src="https://bbbootstrap.com/assets/js/notify.js?v=1"></script>
    <script src="https://bbbootstrap.com/assets/js/imgur.js?v=1"></script>

    {% for local_css_url in local_css_urls %}
    <link rel="stylesheet" href="{% static local_css_url %}">
{% endfor %}

   <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
   <!-- //for bootstrap working -->
   <link href="https://fonts.googleapis.com/css?family=Caveat|Gloria+Hallelujah|Handlee|Modak|Nanum+Pen+Script|Roboto|Source+Sans+Pro&display=swap" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,900,900italic,700italic' rel='stylesheet' type='text/css'>
    <script>
        UPLOADCARE_PUBLIC_KEY = "4b92b91744f8fad64594";
      </script>
      <script charset="utf-8" src="https://ucarecdn.com/libs/widget/3.6.0/uploadcare.full.min.js"></script>
</head>
<body class="index-page sidebar-collapse">

{% block content %}



{% endblock %}
<!--   Core JS Files   -->


{% include 'shop/homepage/page/js.html' %}

{% for local_js_url in local_js_urls %}
<script src="{% static local_js_url %}"></script>
{% endfor %}



</body>
</html>

shop/templates/shop/homepage/basecarousel.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="description" content="jadili mall ">
    <meta name="keywords" content="">
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <title>{% block title %}jadili mall {% endblock %}</title>  <!--Curio On-line -->
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

    <link rel="shortcut icon" type="image/png" href="{% static 'images/u.png' %}"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'css/carouselstyles.css' %}">


</head>
<body>
    

{% block content %}



{% endblock %}







<script>


        /*
            Carousel
        */
        $('#carousel-example').on('slide.bs.carousel', function (e) {
            /*
                CC 2.0 License Iatek LLC 2018 - Attribution required
            */
            var $e = $(e.relatedTarget);
            var idx = $e.index();
            var itemsPerSlide = 5;
            var totalItems = $('.carousel-item').length;
         
            if (idx >= totalItems-(itemsPerSlide-1)) {
                var it = itemsPerSlide - (totalItems - idx);
                for (var i=0; i<it; i++) {
                    // append slides to end
                    if (e.direction=="left") {
                        $('.carousel-item').eq(i).appendTo('.carousel-inner');
                    }
                    else {
                        $('.carousel-item').eq(0).appendTo('.carousel-inner');
                    }
                }
            }
        });</script>

</body>
</html>

shop/templates/shop/homepage/navbar.html
{% load static %}
{% load bootstrap4 %}

<!----------nav -------------------------------------------->
  <nav  class="navbar  bg-dark fixed-top  navbar-expand-lg " color-on-scroll="100" id="sectionsNav"  style=" box-shadow: 0 8px 10px 1px rgba(0, 0, 0, 0.14), 0 3px 14px 2px rgba(0, 0, 0, 0.12), 0 5px 5px -3px rgba(0, 0, 0, 0.2); ">
    <div class="container" >
   <div class="navbar-translate">
		<a><img src="../../static/img/jadili.png " alt="" style="width:180px; height:100px "></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>



      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">    
        
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              <!-- <i class="material-icons">apps</i> Components --> Shop
            </a>
            <div class="dropdown-menu dropdown-with-icons">
              <a href="{% url 'shop:product_list' %}"  class="dropdown-item">
                <i class="material-icons">layers</i> Shop
              </a>
              <!-- <a href="{% url 'shop:product_list' %}"  class="dropdown-item">
                <i class="material-icons">line_style</i> All Components
              </a>
              <a href="{% url 'shop:product_list' %}"  class="dropdown-item">
                <i class="material-icons">content_paste</i> Documentation
              </a> -->
            </div>
          </li>
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              <i class="material-icons">view_day</i> About
            </a>
            <div class="dropdown-menu dropdown-with-icons">
              <a href="{% url 'shop:about' %}"  class="dropdown-item">
                <i class="material-icons">dns</i> Our story
              </a>
              <a href="{% url 'shop:contact' %}"  class="dropdown-item">
                <i class="material-icons">call</i> Contact Us
              </a>
              <a href="{% url 'shop:about' %}" class="dropdown-item">
                <i class="material-icons">list</i> FAQs
              </a>
             
            </div>
          </li>
      
          <li class="button-container nav-item iframe-extern">
            <a href="/cart" class="btn  btn-primary  btn-round btn-block">
              <i class="material-icons">shopping_cart</i> {{ totail_items }}  {{ totail_items|pluralize }}, KSH {{ cart.get_total_price }}
            </a>
          </li>

          <li>

         
              <div class="dropdown ">
                  {% if request.user.is_authenticated %}
                <button class="dropdown-toggle btn btn-primary btn-round btn-block "  type="button" id="multiDropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Welcome  {{ request.user.first_name  }}
                </button>
                <div class="dropdown-menu dropdown-with-icons" aria-labelledby="multiDropdownMenu">
              

                    <a class="dropdown-item"  onclick="ajax_logout();"><i class="material-icons">person</i> Log out</a>

                    <a class="dropdown-item"  data-toggle="modal" data-target="#ordertrackmodal"> <i class="material-icons">motorcycle</i> Track Order</a>

               
                </div>
                {% else %}
                <button class="dropdown-toggle btn btn-primary btn-round btn-block "  type="button" id="multiDropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  My Account
                </button>
                <div class="dropdown-menu dropdown-with-icons" aria-labelledby="multiDropdownMenu">
                    <a class="dropdown-item"  href="/redirected_login"> <i class="material-icons">account_circle</i> Login</a>
                  <a class="dropdown-item"  href="/redirected-register"> <i class="material-icons">account_circle</i> Sign up</a>
                 
                </div>
                {% endif %}
              </div>
           
        </li>
          <li class="dropdown nav-item">
              <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                <i class="material-icons">store</i> sell with us
              </a>
              <div class="dropdown-menu dropdown-with-icons">
                 
                  <a class="dropdown-item"  data-toggle="modal" data-target="#noticeModal"> <i class="material-icons"></i> How it works</a>
                <a href="{% url 'shop:vendorrequest' %}" class="dropdown-item">
                  <i class="material-icons">location_on</i>Seller Center
                </a>
                <a href="{% url 'shop:Vendorfaqs' %}"class="dropdown-item">
                  <i class="material-icons">question_answer</i> FAQs
                </a>
               
              </div>
            </li>


   
        </ul>
      </div>
    </div>
  </nav>

  <!--------- end of nav -------------------------------->




<!--------         modal ----------------------------------------------------->


<div id="ajax_response_login"></div>
<div id="ajax_response_register"></div>
{% include "shop/homepage/page/jsmodal.html" %}


<!-------- end modal -------------------------------------------------------------->