cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url ,include
from django.contrib.auth import views
from django.urls import path, re_path






urlpatterns = [
   

      # Django JET dashboard URLS
    re_path('admin/', admin.site.urls),
    re_path(r'', include('registration.urls')),
    re_path(r'', include('login.urls')),
    re_path(r'', include('account.urls')),
    re_path(r'cart', include('cart.urls')),
    re_path(r'orders/', include('orders.urls')),
    re_path(r'', include('shop.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include
from . import views

app_name = 'shop'


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^vendorrequest/', views.vendorrequest, name='vendorrequest'),
    url(r'^Vendorfaqs/', views.Vendorfaqs, name='Vendorfaqs'),
    url(r'^log/', views.log, name='log'),
    url(r'^about/', views.about, name='about'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^mens/', views.mens, name='mens'),
    url(r'^womens/', views.womens, name='womens'),
    url(r'^decorbeauty/', views.decorbeauty, name='decorbeauty'),
    url(r'^homeaccesories/', views.homeaccesories, name='homeaccesories'),
    url(r'^shop/', views.product_list, name='product_list'),
    url(r'^negotiate/price', views.client_price, name='client_price'),
    url(r'^negotiate/', views.negotiate, name='negotiate'),
    

   
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail, name='product_detail'),

    url(r'^(?P<subcategory_slug>[-\w]+)/$',
        views.subcategory_list, name='product_list_by_subcategory'),
    url(r'^(?P<minicategory_slug>[-\w]+)/$',
        views.minicategory_list, name='product_list_by_minicategory')




]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/forms.py
from django import forms

class NegotiateForm(forms.Form):
    client_price = forms.CharField(label='Your price', max_length=100)

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, SubCategory, MiniCategory
from .forms import NegotiateForm
from cart.forms import CartAddProductForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from account.models import Client
from django.shortcuts import redirect


# @login_required(login_url='/accounts/login/')
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)

    return render(request, 'shop/product/list.html',   context={
        'category': category,
        'categories': categories,
        'products': products,
        'tab': 'shop',
        'local_css_urls': ["css3/easy-responsive-tabs.css",
                           "css3/material-kit.min1036.css",
                           "css3/demo.css",
                           "css3/vertical-nav.css"],
        'local_js_urls': ["core/jquery.min.js",
                          "core/popper.min.js",
                          "core/bootstrap-material-design.min.js",
                          "js3/vertical-nav.js",
                          "js3/material-kit.min1036.js",
                          "js3/demo.js",
                          "js3/buttons.js",
                          "js3/modernizr.js",
                          "js3/bootstrap.min.js",
                          "js3/plugins/moment.min.js ",
                          "js3/plugins/bootstrap-datetimepicker.js",
                          "js3/plugins/jquery.flexisel.js",
                          "js3/plugins/jquery.sharrre.js",
                          "js3/plugins/nouislider.min.js",
                          "js3/plugins/bootstrap-selectpicker.js",
                          "js3/plugins/bootstrap-tagsinput.js",
                          "js3/plugins/jasny-bootstrap.min.js"],
    })


def subcategory_list(request, subcategory_slug=None):
    subcategory = None
    subcategories = Category.SubCategory.objects.all()
    products = Product.subcategory.objects.filter(available=True)
    if category_slug:
        subcategory = get_object_or_404(SubCategory, slug=SubCategory_slug)
        products = Product.objects.filter(subcategory=subcategory)

    context = {

        'subcategory': subcategory,
        'subcategories': subcategories,
        'products': products,

    }
    return render(request, 'shop/product/sublist.html', context)


def minicategory_list(request, minicategory_slug=None):
    minicategory = None
    minicategories = Category.SubCategory.MiniCategory.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        minicategory = get_object_or_404(MiniCategory, slug=MiniCategory_slug)
        products = Product.objects.filter(minicategory=minicategory)

    context = {

        'minicategory': minicategory,
        'minicategories': minicategories,
        'products': products,

    }

    return render(request, 'shop/product/minilist.html', context)

# @login_required(login_url='/accounts/login/')
# def product_detail(request, id, slug):
#     product = get_object_or_404(Product, id=id, slug=slug, available=True)
#     cart_product_form = CartAddProductForm()
#     context = {
#         'product': product,
#         'cart_product_form': cart_product_form
#     }
#     return render(request, 'shop/product/detail.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'shop/product/detail.html',
                  context={
                      'product': product,
                      'cart_product_form': cart_product_form,
                      'local_css_urls': ["css3/easy-responsive-tabs.css",
                                         "css3/material-kit.min1036.css",
                                         "css3/demo.css",
                                         "css3/vertical-nav.css"],
                      'local_js_urls': ["core/jquery.min.js",
                                        "core/popper.min.js",
                                        "core/bootstrap-material-design.min.js",
                                        "js3/vertical-nav.js",
                                        "js3/material-kit.min1036.js",
                                        "js3/demo.js",
                                        "js3/buttons.js",
                                        "js3/modernizr.js",
                                        "js3/bootstrap.min.js",
                                        "js3/plugins/moment.min.js ",
                                        "js3/plugins/bootstrap-datetimepicker.js",
                                        "js3/plugins/jquery.flexisel.js",
                                        "js3/plugins/jquery.sharrre.js",
                                        "js3/plugins/nouislider.min.js",
                                        "js3/plugins/bootstrap-selectpicker.js",
                                        "js3/plugins/bootstrap-tagsinput.js",
                                        "js3/plugins/jasny-bootstrap.min.js"],
                  })


# homepage view

def home(request, category_slug=None, subcategory_slug=None, minicategory_slug=None):
    category = None
    subcategory = None
    minicategory = None
    categories = Category.objects.all()
    subcategories = SubCategory.objects.all()
    minicategories = MiniCategory.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        subcategories = SubCategory.objects.filter(category=category)

    # if subcategory_slug:
    #     subcategory = get_object_or_404(SubCategory, slug=subcategory_slug)
    #     minicategories = MiniCategory.objects.filter(available=True)

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'subcategories': subcategories,
        'minicategories ': minicategories,
        'subcategory': subcategory,
        'minicategory': minicategory,
    }

    return render(request, 'shop/homepage/page/home.html',   context={
        'category': category,
        'categories': categories,
        'products': products,
        'subcategories': subcategories,
        'minicategories': minicategories,
        'subcategory': subcategory,
        'minicategory': minicategory,

        'tab': 'shop',
        'local_css_urls': ["css3/easy-responsive-tabs.css",
                           "css3/material-kit.min1036.css",
                           "css3/demo.css",
                           "css3/vertical-nav.css"],
        'local_js_urls': ["core/jquery.min.js",
                          "core/popper.min.js",
                          "core/bootstrap-material-design.min.js",
                          "js3/vertical-nav.js",
                          "js3/material-kit.min1036.js",
                          "js3/demo.js",
                          "js3/buttons.js",
                          "js3/modernizr.js",
                          "js3/bootstrap.min.js",
                          "js3/plugins/moment.min.js ",
                          "js3/plugins/bootstrap-datetimepicker.js",
                          "js3/plugins/jquery.flexisel.js",
                          "js3/plugins/jquery.sharrre.js",
                          "js3/plugins/nouislider.min.js",
                          "js3/plugins/bootstrap-selectpicker.js",
                          "js3/plugins/bootstrap-tagsinput.js",
                          "js3/plugins/jasny-bootstrap.min.js"],
    })


def log(request):
    return render(request, 'shop/product/login2.html', {
        'tab': 'registration',
        'local_css_urls': ["css3/easy-responsive-tabs.css",
                           "css3/material-kit.min1036.css",
                           "css3/demo.css",
                           "css3/vertical-nav.css"],
        'local_js_urls': ["core/jquery.min.js",
                          "core/popper.min.js",
                          "core/bootstrap-material-design.min.js",
                          "js3/vertical-nav.js",
                          "js3/material-kit.min1036.js",
                          "js3/demo.js",
                          "js3/buttons.js",
                          "js3/modernizr.js",
                          "js3/bootstrap.min.js",
                          "js3/plugins/moment.min.js ",
                          "js3/plugins/bootstrap-datetimepicker.js",
                          "js3/plugins/jquery.flexisel.js",
                          "js3/plugins/jquery.sharrre.js",
                          "js3/plugins/nouislider.min.js",
                          "js3/plugins/bootstrap-selectpicker.js",
                          "js3/plugins/bootstrap-tagsinput.js",
                          "js3/plugins/jasny-bootstrap.min.js"],
    })


def vendorrequest(request):
    return render(request, 'shop/homepage/page/vendorrequest.html', {
        'tab': 'vendor',
        'local_css_urls': ["css3/easy-responsive-tabs.css",
                           "css3/material-kit.min1036.css",
                           "css3/demo.css",
                           "css3/vertical-nav.css"],
        'local_js_urls': ["js3/vertical-nav.js",
                          "js3/material-kit.min1036.js",
                          "js3/demo.js",
                          "js3/buttons.js",
                          "js3/modernizr.js",

                          "js3/jquery.min.js",
                          "js3/bootstrap.min.js",

shop/views/forgot_password.py
import json
import random, string
from django.shortcuts import render
from django.core import serializers
from landpage.form import ForgotPasswordForm
from django.http import HttpResponse
from django.conf import settings
from django.contrib.auth.models import User
from django.conf import settings
from django.core.mail import send_mail

def forgot_password_page(request):
    form = ForgotPasswordForm()
    return render(request, 'offlandpage/page/forgot_password.html',{
        'form': form,
        'tab': 'forget_password',
        'local_css_urls': ["css/offlandpage.css",
                            "bower_components/bootstrap/dist/css/bootstrap.min.css"],
        'local_js_urls': ["bower_components/jquery/dist/jquery.min.js",
                           "bower_components/bootstrap/dist/js/bootstrap.min.js",],
    })


def reset_password(request):
    response_data = {'status' : 'failure', 'message' : 'unknown error occured' }
    if request.is_ajax():
        if request.method == 'POST':
            form = ForgotPasswordForm(request.POST)
            # Validate the form: the captcha field will automatically
            # check the input
            if form.is_valid():
                # Get the email and then create a random password for the client
                # and send the client the new password to their email address.
                email = request.POST['email']
                new_password = create_random_password(email)
                response_data = send_email(email, new_password)
            else:
                response_data = {'status' : 'failed', 'message' : json.dumps(form.errors)}
    return HttpResponse(json.dumps(response_data), content_type="application/json")


def random_word(length):
    return ''.join(random.choice("abcdefghijklmnopqrstuvwxyz123467890") for i in range(length))


def create_random_password(email):
    # Create new password
    new_password = random_word(8)
    
    # Update the user account
    user = User.objects.get(email=email)
    user.set_password(new_password)
    user.save()
    
    # Return the new password
    return new_password


def send_email(email, new_password):
    if settings.EMAIL_HOST_USER is '' or settings.EMAIL_HOST_PASSWORD is '':
        return {'status' : 'failed', 'message' : 'cannot change password, emailer is offline, please check back later' }
    
    text = "Your new password is: " + new_password
            
    send_mail(
        "New Password",
        text,
        settings.EMAIL_HOST_USER,
        [email],
        fail_silently=False
    )
    return {'status' : 'success', 'message' : 'successfully registered' }

shop/views/google.py
from django.shortcuts import render
from django.core import serializers
import json
from django.http import HttpResponse
from django.conf import settings


def google_verify_page(request):
    return render(request, 'misc/google.html',{})

shop/views/landpageprod.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings

shop/views/privacy.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings


def privacy_page(request):
    return render(request, 'offlandpage/page/privacy.html',{
        'tab': 'privacy',
        'local_css_urls': ["css/offlandpage.css",
                            "bower_components/bootstrap/dist/css/bootstrap.min.css"],
        'local_js_urls': ["bower_components/jquery/dist/jquery.min.js",
                           "bower_components/bootstrap/dist/js/bootstrap.min.js",],
    })

shop/views/terms.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings


def terms_page(request):
    return render(request, 'offlandpage/page/terms.html',{
        'tab': 'terms',
        'local_css_urls': ["css/offlandpage.css",
                            "bower_components/bootstrap/dist/css/bootstrap.min.css"],
        'local_js_urls': ["bower_components/jquery/dist/jquery.min.js",
                           "bower_components/bootstrap/dist/js/bootstrap.min.js",],
    })

shop/views/txt.py
import json
from django.shortcuts import render
from django.core import serializers
from django.http import HttpResponse
from django.conf import settings


def robots_txt_page(request):
    return render(request, 'misc/robots.txt', {}, content_type="text/plain")


def humans_txt_page(request):
    return render(request, 'misc/humans.txt', {}, content_type="text/plain")


def terms_txt_page(request):
    return render(request, 'misc/terms.txt', {}, content_type="text/plain")


def privacy_txt_page(request):
    return render(request, 'misc/privacy.txt', {}, content_type="text/plain")

shop/templates/shop/base.html
background-color: #212121!important;
box-shadow: 0 4px 20px 0 rgba(0, 0, 0, .14), 0 7px 12px -5px rgba(33, 33, 33, .46)

shop/templates/shop/discount.html
{% load static %}


{% block content %}
Thank you for making {{client_orders}} previous orders ,
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


{% endblock content %}

shop/templates/shop/navbar.html
{% load static %}
{% load bootstrap4 %}
<nav>

<!--  header Login signup nav  ------------>
<div class="header" id="home">
	<div class="container">
			<div class="col-md-4 logo_agile">
          <a><img src="../../static/img/jadili.png " href="" alt="" style="width:180px; height:100px "></a>

				</div>
		<ul class="nav navbar-right">
				<li class="dropdown">
			      	{% if request.user.is_authenticated %}
					         <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">Welcome  {{ request.user.username }}<b class="caret"></b></a>
							<ul class="dropdown-menu">
							     <li><a  onclick="ajax_logout();" style="color:black">logout</a></li>
							</ul>
				</li>
		</ul>
					        	{% else %}
	   <ul>
		    <li> <a href="/redirected_login"><i aria-hidden="true"></i> Sign In </a></li>
		   	<li> <a href="/admin"><i class="fa fa-unlock-alt"aria-hidden="true"></i>Admin Login</a></li>
					          {% endif %}
		</ul>
	</div>
</div>
<!--  //end of header Login signup nav  ----------------------------------------->


<!-- start of items navbar ------------------------------------------>
<div class="ban-top" style="box-shadow: 0 4px 20px 0 rgba(0, 0, 0, .14), 0 7px 12px -5px rgba(33, 33, 33, .46);">
	<div class="container" >
		<div class="top_nav_left">
			<nav class="navbar navbar-default">
			  <div class="container-fluid">

				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
				  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				  </button>
        </div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
				  <ul class="nav navbar-nav menu__list">
					<li class="active menu__item menu__item--current"><a class="menu__link" href="{% url 'shop:home' %}">Home <span class="sr-only">(current)</span></a></li>
					<li class=" menu__item"><a class="menu__link" href="{% url 'shop:product_list' %}">Shop</a></li>
					<li class=" menu__item"><a class="menu__link" href="{% url 'shop:about' %}">about</a></li>
					<li class="dropdown menu__item">
						<a href="{% url 'shop:mens' %}" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Men's wear <span class="caret"></span></a>
							<ul class="dropdown-menu multi-column columns-3">
								<div class="agile_inner_drop_nav_info">
									<div class="col-sm-6 multi-gd-img1 multi-gd-text ">
										<a href="{% url 'shop:mens' %}"><img src="{% static "images/top2.jpg" %}" alt=" "/></a>
									</div>
									<div class="col-sm-3 multi-gd-img">
										<ul class="multi-column-dropdown">
											<li><a href="{% url 'shop:mens' %}">Clothing</a></li>
											<li><a href="{% url 'shop:mens' %}">Wallets</a></li>
											<li><a href="{% url 'shop:mens' %}">Footwear</a></li>
											<li><a href="{% url 'shop:mens' %}">Watches</a></li>
											<li><a href="{% url 'shop:mens' %}">Accessories</a></li>
											<li><a href="{% url 'shop:mens' %}">Bags</a></li>
											<li><a href="{% url 'shop:mens' %}">Caps & Hats</a></li>
										</ul>
									</div>
									<div class="col-sm-3 multi-gd-img">
										<ul class="multi-column-dropdown">
											<li><a href= "{% url 'shop:mens' %}">Jewellery</a></li>
											<li><a href="{% url 'shop:mens' %}">Sunglasses</a></li>
											<li><a href="{% url 'shop:mens' %}">Perfumes</a></li>
											<li><a href="{% url 'shop:mens' %}">Beauty</a></li>
											<li><a href="{% url 'shop:mens' %}">Shirts</a></li>
											<li><a href="{% url 'shop:mens' %}">Sunglasses</a></li>
											<li><a href="{% url 'shop:mens' %}">Swimwear</a></li>
										</ul>
									</div>
									<div class="clearfix"></div>
								</div>
							</ul>
					</li>
					<li class="dropdown menu__item">
						<a href="{% url 'shop:womens' %}" class="dropdown-toggle menu__link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Women's wear <span class="caret"></span></a>
							<ul class="dropdown-menu multi-column columns-3">
								<div class="agile_inner_drop_nav_info">
									<div class="col-sm-3 multi-gd-img">
										<ul class="multi-column-dropdown">
											<li><a href="{% url 'shop:womens' %}" >Clothing</a></li>
											<li><a href="{% url 'shop:womens' %}" >Wallets</a></li>
											<li><a href="{% url 'shop:womens' %}" >Footwear</a></li>
											<li><a href="{% url 'shop:womens' %}" >Watches</a></li>
											<li><a href="{% url 'shop:womens' %}" >Accessories</a></li>
											<li><a href="{% url 'shop:womens' %}" >Bags</a></li>
											<li><a href="{% url 'shop:womens' %}" >Caps & Hats</a></li>
										</ul>
									</div>
									<div class="col-sm-3 multi-gd-img">
										<ul class="multi-column-dropdown">
											<li><a href="{% url 'shop:womens' %}" >Jewellery</a></li>
											<li><a href="{% url 'shop:womens' %}" >Sunglasses</a></li>
											<li><a href="{% url 'shop:womens' %}" >Perfumes</a></li>
											<li><a href="{% url 'shop:womens' %}" >Shirts</a></li>
											<li><a href="{% url 'shop:womens' %}" >Sunglasses</a></li>
											<li><a href="{% url 'shop:womens' %}" >Swimwear</a></li>
										</ul>
									</div>
									<div class="col-sm-6 multi-gd-img multi-gd-text ">
										<a href="{% url 'shop:womens' %}" ><img src="{% static "images/loginpic.jpeg" %}" alt=" "/></a>
									</div>
									<div class="clearfix"></div>
								</div>
							</ul>
					</li>
					<li class="menu__item dropdown">
					   <a class="menu__link" href="{% url 'shop:homeaccesories' %}" class="dropdown-toggle" data-toggle="dropdown">Home & Decor <b class="caret"></b></a>
								<ul class="dropdown-menu agile_short_dropdown">
									<li><a href="{% url 'shop:homeaccesories' %}">Home Accesories</a></li>
									<li><a href="{% url 'shop:decorbeauty' %}">Decor & Beauty</a></li>
								</ul>
					</li>
					<li class=" menu__item"><a class="menu__link" href="{% url 'shop:contact' %}">Contact</a></li>
				  </ul>
          <div class="top_nav_right">
            <div class="box_1">

              {% with totail_items=cart|length %}
                  {% if cart|length > 0 %}
                      My Shopping Order:
                      <a href="{% url "cart:cart_detail" %}" >
                          {{ totail_items }} <button type="button" class="btn btn-primary btn-lg">item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}</button>
                      </a>
                      {% else %}
                      Your cart is empty.  {{ totail_items }}  {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
                  {% endif %}
              {% endwith %}

                  </div>
          </div>
				</div>
			  </div>
    </div>

		<!-- end of item list navbar --------------------------->

		<!-- login modal form Modal1 -------------------------------------->
			<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
				<div class="modal-dialog">
					<!-- Modal content-->
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal">&times;</button>
						</div>
							<div class="modal-body modal-body-sub_agile">
							<div class="col-md-8 modal_body_left modal_body_left1">
							<h3 class="agileinfo_sign">Sign In <span>Now</span></h3>
										<form action ="/accounts/login/" method="post">
								<div class="styled-input agile-styled-input-top">
									<input type="text" name="Name" required="">
									<label>Name</label>
									<span></span>
								</div>
								<div class="styled-input">
									<input type="email" name="Email" required="">
									<label>Email</label>
									<span></span>
								</div>
								<input type="submit" value="Sign In">
							</form>
							<br>
							<strong>or Sign in using</strong>
							<ul class="">
								<li><a href="#" class="facebook">
									  
									  <div class="Front"><i class="fa fa-facebook" aria-hidden="true"></i></div></a></li>
								<li><a href="#" class="twitter">
									 
									  <div class="front"><i class="fa fa-twitter" aria-hidden="true"></i></div></a></li>
								<li><a href="#" class="instagram">
									 
									  <div class="front"><i class="fa fa-instagram" aria-hidden="true"></i></div></a></li>
								<li><a href="#" class="pinterest">
									  
									  <div class="front"><i class="fa fa-linkedin" aria-hidden="true"></i></div></a></li>
                              </ul>
															<div class="clearfix"></div>
															<p><a href="#" data-toggle="modal" data-target="#myModal2" > Don't have an account?</a></p>

							</div>
							<div class="col-md-4 modal_body_right modal_body_right1">
								<img src="{% static "images/loginpic.jpeg" %}" alt=" "/>
							</div>
							<div class="clearfix"></div>
						</div>
					</div>
					<!-- //Modal content-->
				</div>
			</div>

		</nav>
	<!-- //Modal1 -->
	<!-- Modal2 -->
			<div class="modal fade" id="myModal2" tabindex="-1" role="dialog">
				<div class="modal-dialog">
					<!-- Modal content-->
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal">&times;</button>
						</div>
							<div class="modal-body modal-body-sub_agile">
							<div class="col-md-8 modal_body_left modal_body_left1">
							<h3 class="agileinfo_sign">Sign Up <span>Now</span></h3>
							 <form action"/accounts/register/" method="post">
								<div class="styled-input agile-styled-input-top">
									<input type="text" name="Name" required="">
									<label>Name</label>
									<span></span>
								</div>
								<div class="styled-input">
									<input type="email" name="Email" required="">
									<label>Email</label>
									<span></span>
								</div>
								<div class="styled-input">
									<input type="password" name="password" required="">
									<label>Password</label>
									<span></span>
								</div>
								<div class="styled-input">
									<input type="password" name="Confirm Password" required="">
									<label>Confirm Password</label>
									<span></span>
								</div>
								<input type="submit" value="Sign Up">
							</form>
							<br>
							 <strong>or Sign in using</strong>
							 <ul class="">
								<li><a href="#" class="facebook">
									  
									  <div class="Front"><i class="fa fa-facebook" aria-hidden="true"></i></div></a></li>
								<li><a href="#" class="twitter">
									 
									  <div class="front"><i class="fa fa-twitter" aria-hidden="true"></i></div></a></li>
								<li><a href="#" class="instagram">
									 
									  <div class="front"><i class="fa fa-instagram" aria-hidden="true"></i></div></a></li>
								<li><a href="#" class="pinterest">
									  
									  <div class="front"><i class="fa fa-linkedin" aria-hidden="true"></i></div></a></li>
                              </ul>
															<div class="clearfix"></div>
															<p><a href="#">By clicking register, I agree to your terms</a></p>

							</div>
							<div class="col-md-4 modal_body_right modal_body_right1">
								<img src="{% static "images/loginpic.jpeg" %}"alt=" "/>
							</div>
							<div class="clearfix"></div>
						</div>
					</div>
					<!-- //Modal content-->
				</div>
			</div>
	<!-- //Modal2 -->